/*
 Navicat MySQL Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 50505
 Source Host           : localhost
 Source Database       : ofbizolap

 Target Server Type    : MySQL
 Target Server Version : 50505
 File Encoding         : utf-8

 Date: 04/26/2017 16:24:13 PM
*/

SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
--  Table structure for `CURRENCY_DIMENSION`
-- ----------------------------
DROP TABLE IF EXISTS `CURRENCY_DIMENSION`;
CREATE TABLE `CURRENCY_DIMENSION` (
  `DIMENSION_ID` varchar(20) NOT NULL,
  `CURRENCY_ID` varchar(20) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime DEFAULT NULL,
  `CREATED_STAMP` datetime DEFAULT NULL,
  `CREATED_TX_STAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`DIMENSION_ID`),
  KEY `CRRNC_DMNSN_TXSTMP` (`LAST_UPDATED_TX_STAMP`),
  KEY `CRRNC_DMNSN_TXCRTS` (`CREATED_TX_STAMP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Records of `CURRENCY_DIMENSION`
-- ----------------------------
BEGIN;
INSERT INTO `CURRENCY_DIMENSION` VALUES ('_NA_', null, 'Currency Not Set.', '2017-04-26 15:42:14', '2017-04-26 15:42:14', '2017-04-26 15:42:14', '2017-04-26 15:42:14'), ('_NF_', null, 'Currency Not Found.', '2017-04-26 15:42:14', '2017-04-26 15:42:14', '2017-04-26 15:42:14', '2017-04-26 15:42:14');
COMMIT;

-- ----------------------------
--  Table structure for `DATE_DIMENSION`
-- ----------------------------
DROP TABLE IF EXISTS `DATE_DIMENSION`;
CREATE TABLE `DATE_DIMENSION` (
  `DIMENSION_ID` varchar(20) NOT NULL,
  `DATE_VALUE` date DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `DAY_NAME` varchar(60) DEFAULT NULL,
  `DAY_OF_MONTH` decimal(20,0) DEFAULT NULL,
  `DAY_OF_YEAR` decimal(20,0) DEFAULT NULL,
  `MONTH_NAME` varchar(60) DEFAULT NULL,
  `MONTH_OF_YEAR` decimal(20,0) DEFAULT NULL,
  `YEAR_NAME` decimal(20,0) DEFAULT NULL,
  `WEEK_OF_MONTH` decimal(20,0) DEFAULT NULL,
  `WEEK_OF_YEAR` decimal(20,0) DEFAULT NULL,
  `YEAR_MONTH_DAY` varchar(60) DEFAULT NULL,
  `YEAR_AND_MONTH` varchar(60) DEFAULT NULL,
  `WEEKDAY_TYPE` varchar(60) DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime DEFAULT NULL,
  `CREATED_STAMP` datetime DEFAULT NULL,
  `CREATED_TX_STAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`DIMENSION_ID`),
  KEY `DT_DMNSN_TXSTMP` (`LAST_UPDATED_TX_STAMP`),
  KEY `DT_DMNSN_TXCRTS` (`CREATED_TX_STAMP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Records of `DATE_DIMENSION`
-- ----------------------------
BEGIN;
INSERT INTO `DATE_DIMENSION` VALUES ('_NA_', null, 'Date Not Set.', null, null, null, null, null, null, null, null, null, null, null, '2017-04-26 15:42:14', '2017-04-26 15:42:14', '2017-04-26 15:42:14', '2017-04-26 15:42:14'), ('_NF_', null, 'Date Not Found.', null, null, null, null, null, null, null, null, null, null, null, '2017-04-26 15:42:14', '2017-04-26 15:42:14', '2017-04-26 15:42:14', '2017-04-26 15:42:14');
COMMIT;

-- ----------------------------
--  Table structure for `INVENTORY_ITEM_FACT`
-- ----------------------------
DROP TABLE IF EXISTS `INVENTORY_ITEM_FACT`;
CREATE TABLE `INVENTORY_ITEM_FACT` (
  `INVENTORY_ITEM_ID` varchar(20) NOT NULL,
  `FACILITY_ID` varchar(20) DEFAULT NULL,
  `PRODUCT_DIM_ID` varchar(20) DEFAULT NULL,
  `ORIG_CURRENCY_DIM_ID` varchar(20) DEFAULT NULL,
  `INVENTORY_DATE_DIM_ID` varchar(20) DEFAULT NULL,
  `QUANTITY_ON_HAND_TOTAL` decimal(18,6) DEFAULT NULL,
  `AVAILABLE_TO_PROMISE_TOTAL` decimal(18,6) DEFAULT NULL,
  `UNIT_COST` decimal(18,6) DEFAULT NULL,
  `SOLDOUT_AMOUNT` decimal(18,6) DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime DEFAULT NULL,
  `CREATED_STAMP` datetime DEFAULT NULL,
  `CREATED_TX_STAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`INVENTORY_ITEM_ID`),
  KEY `IIF_INVPRODUCT` (`PRODUCT_DIM_ID`),
  KEY `IIF_INVCURRENCY` (`ORIG_CURRENCY_DIM_ID`),
  KEY `IIF_INVDATE` (`INVENTORY_DATE_DIM_ID`),
  KEY `INVR_ITM_FCT_TXSTP` (`LAST_UPDATED_TX_STAMP`),
  KEY `INVR_ITM_FCT_TXCRS` (`CREATED_TX_STAMP`),
  CONSTRAINT `IIF_INVCURRENCY` FOREIGN KEY (`ORIG_CURRENCY_DIM_ID`) REFERENCES `CURRENCY_DIMENSION` (`DIMENSION_ID`),
  CONSTRAINT `IIF_INVDATE` FOREIGN KEY (`INVENTORY_DATE_DIM_ID`) REFERENCES `DATE_DIMENSION` (`DIMENSION_ID`),
  CONSTRAINT `IIF_INVPRODUCT` FOREIGN KEY (`PRODUCT_DIM_ID`) REFERENCES `PRODUCT_DIMENSION` (`DIMENSION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `PRODUCT_DIMENSION`
-- ----------------------------
DROP TABLE IF EXISTS `PRODUCT_DIMENSION`;
CREATE TABLE `PRODUCT_DIMENSION` (
  `DIMENSION_ID` varchar(20) NOT NULL,
  `PRODUCT_ID` varchar(20) DEFAULT NULL,
  `PRODUCT_TYPE` varchar(255) DEFAULT NULL,
  `BRAND_NAME` varchar(100) DEFAULT NULL,
  `INTERNAL_NAME` varchar(255) DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime DEFAULT NULL,
  `CREATED_STAMP` datetime DEFAULT NULL,
  `CREATED_TX_STAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`DIMENSION_ID`),
  KEY `PRDCT_DMNSN_TXSTMP` (`LAST_UPDATED_TX_STAMP`),
  KEY `PRDCT_DMNSN_TXCRTS` (`CREATED_TX_STAMP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Records of `PRODUCT_DIMENSION`
-- ----------------------------
BEGIN;
INSERT INTO `PRODUCT_DIMENSION` VALUES ('_NA_', null, null, null, null, '2017-04-26 15:42:14', '2017-04-26 15:42:14', '2017-04-26 15:42:14', '2017-04-26 15:42:14'), ('_NF_', null, null, null, null, '2017-04-26 15:42:14', '2017-04-26 15:42:14', '2017-04-26 15:42:14', '2017-04-26 15:42:14');
COMMIT;

-- ----------------------------
--  Table structure for `SALES_INVOICE_ITEM_FACT`
-- ----------------------------
DROP TABLE IF EXISTS `SALES_INVOICE_ITEM_FACT`;
CREATE TABLE `SALES_INVOICE_ITEM_FACT` (
  `INVOICE_ID` varchar(20) NOT NULL,
  `INVOICE_ITEM_SEQ_ID` varchar(20) NOT NULL,
  `ORDER_ID` varchar(20) DEFAULT NULL,
  `INVOICE_DATE_DIM_ID` varchar(20) DEFAULT NULL,
  `PRODUCT_DIM_ID` varchar(20) DEFAULT NULL,
  `BILL_TO_CUSTOMER_DIM_ID` varchar(20) DEFAULT NULL,
  `ORIG_CURRENCY_DIM_ID` varchar(20) DEFAULT NULL,
  `QUANTITY` decimal(18,6) DEFAULT NULL,
  `EXT_GROSS_AMOUNT` decimal(18,3) DEFAULT NULL,
  `EXT_DISCOUNT_AMOUNT` decimal(18,3) DEFAULT NULL,
  `EXT_NET_AMOUNT` decimal(18,3) DEFAULT NULL,
  `EXT_TAX_AMOUNT` decimal(18,3) DEFAULT NULL,
  `EXT_MAN_FIXED_COST` decimal(18,3) DEFAULT NULL,
  `EXT_MAN_VAR_COST` decimal(18,3) DEFAULT NULL,
  `EXT_STORAGE_COST` decimal(18,3) DEFAULT NULL,
  `EXT_DISTRIBUTION_COST` decimal(18,3) DEFAULT NULL,
  `CONTRIBUTION_AMOUNT` decimal(18,3) DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime DEFAULT NULL,
  `CREATED_STAMP` datetime DEFAULT NULL,
  `CREATED_TX_STAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`INVOICE_ID`,`INVOICE_ITEM_SEQ_ID`),
  KEY `SIIF_INVDATE` (`INVOICE_DATE_DIM_ID`),
  KEY `SIIF_CURRENCY` (`ORIG_CURRENCY_DIM_ID`),
  KEY `SIIF_PRODUCT` (`PRODUCT_DIM_ID`),
  KEY `SLS_INC_ITM_FCT_TP` (`LAST_UPDATED_TX_STAMP`),
  KEY `SLS_INC_ITM_FCT_TS` (`CREATED_TX_STAMP`),
  CONSTRAINT `SIIF_CURRENCY` FOREIGN KEY (`ORIG_CURRENCY_DIM_ID`) REFERENCES `CURRENCY_DIMENSION` (`DIMENSION_ID`),
  CONSTRAINT `SIIF_INVDATE` FOREIGN KEY (`INVOICE_DATE_DIM_ID`) REFERENCES `DATE_DIMENSION` (`DIMENSION_ID`),
  CONSTRAINT `SIIF_PRODUCT` FOREIGN KEY (`PRODUCT_DIM_ID`) REFERENCES `PRODUCT_DIMENSION` (`DIMENSION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `SALES_ORDER_ITEM_FACT`
-- ----------------------------
DROP TABLE IF EXISTS `SALES_ORDER_ITEM_FACT`;
CREATE TABLE `SALES_ORDER_ITEM_FACT` (
  `ORDER_ID` varchar(20) NOT NULL,
  `ORDER_ITEM_SEQ_ID` varchar(20) NOT NULL,
  `ORDER_DATE_DIM_ID` varchar(20) DEFAULT NULL,
  `PRODUCT_DIM_ID` varchar(20) DEFAULT NULL,
  `ORIG_CURRENCY_DIM_ID` varchar(20) DEFAULT NULL,
  `BILL_TO_CUSTOMER_DIM_ID` varchar(20) DEFAULT NULL,
  `PRODUCT_CATEGORY_ID` varchar(20) DEFAULT NULL,
  `PRODUCT_STORE_ID` varchar(20) DEFAULT NULL,
  `SALES_CHANNEL_ENUM_ID` varchar(20) DEFAULT NULL,
  `STATUS_ID` varchar(20) DEFAULT NULL,
  `BRAND` varchar(100) DEFAULT NULL,
  `POD` varchar(100) DEFAULT NULL,
  `ACCOUNT` varchar(100) DEFAULT NULL,
  `QUANTITY` decimal(18,6) DEFAULT NULL,
  `EXT_GROSS_AMOUNT` decimal(18,3) DEFAULT NULL,
  `EXT_GROSS_COST` decimal(18,3) DEFAULT NULL,
  `EXT_DISCOUNT_AMOUNT` decimal(18,3) DEFAULT NULL,
  `EXT_NET_AMOUNT` decimal(18,3) DEFAULT NULL,
  `EXT_SHIPPING_AMOUNT` decimal(18,3) DEFAULT NULL,
  `EXT_TAX_AMOUNT` decimal(18,3) DEFAULT NULL,
  `G_S` decimal(18,3) DEFAULT NULL,
  `G_M_S` decimal(18,3) DEFAULT NULL,
  `G_M_P` decimal(18,3) DEFAULT NULL,
  `G_S_S` decimal(18,3) DEFAULT NULL,
  `G_S_C` decimal(18,3) DEFAULT NULL,
  `G_S_P` decimal(18,3) DEFAULT NULL,
  `G_P` decimal(18,3) DEFAULT NULL,
  `COUNT_ORDER` decimal(18,6) DEFAULT NULL,
  `PRODUCT_PROMO_CODE` varchar(20) DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime DEFAULT NULL,
  `CREATED_STAMP` datetime DEFAULT NULL,
  `CREATED_TX_STAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`ORDER_ID`,`ORDER_ITEM_SEQ_ID`),
  KEY `SOIF_ORDERDATE` (`ORDER_DATE_DIM_ID`),
  KEY `SOIF_CURRENCY` (`ORIG_CURRENCY_DIM_ID`),
  KEY `SOIF_PRODUCT` (`PRODUCT_DIM_ID`),
  KEY `SLS_ORR_ITM_FCT_TP` (`LAST_UPDATED_TX_STAMP`),
  KEY `SLS_ORR_ITM_FCT_TS` (`CREATED_TX_STAMP`),
  CONSTRAINT `SOIF_CURRENCY` FOREIGN KEY (`ORIG_CURRENCY_DIM_ID`) REFERENCES `CURRENCY_DIMENSION` (`DIMENSION_ID`),
  CONSTRAINT `SOIF_ORDERDATE` FOREIGN KEY (`ORDER_DATE_DIM_ID`) REFERENCES `DATE_DIMENSION` (`DIMENSION_ID`),
  CONSTRAINT `SOIF_PRODUCT` FOREIGN KEY (`PRODUCT_DIM_ID`) REFERENCES `PRODUCT_DIMENSION` (`DIMENSION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SET FOREIGN_KEY_CHECKS = 1;
